root: true

parser: '@typescript-eslint/parser'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'

plugins:
  - '@typescript-eslint'

env:
  node: true
  browser: true

rules:
  'react/prop-types': 0
  'no-console': 1
  '@typescript-eslint/no-var-requires': 0
